services: 
  backend: 
    build: backend 
    ports: 
      - '8000:8000'
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - GEMINI_KEY=${GEMINI_KEY}
      - SERPAPI_KEY=${SERPAPI_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CSE_ID=${CSE_ID}
      - GOOGLE_SEARCH_SERVER=${GOOGLE_SEARCH_SERVER}
      - DATABASE_URL=${DATABASE_URL}
      - CLIENT_ID=${CLIENT_ID}
  googlesearchserver:
    build: googlesearchserver
    ports:
      - '80:80'
    environment:
      - GOOGLE_API_KEY1=${GOOGLE_API_KEY1}
      - GOOGLE_SEARCH_ENGINE_ID1=${GOOGLE_SEARCH_ENGINE_ID1}
      - GOOGLE_API_KEY2=${GOOGLE_API_KEY2}
      - GOOGLE_SEARCH_ENGINE_ID2=${GOOGLE_SEARCH_ENGINE_ID2}
      - GOOGLE_API_KEY3=${GOOGLE_API_KEY3}
      - GOOGLE_SEARCH_ENGINE_ID3=${GOOGLE_SEARCH_ENGINE_ID3}
      - GOOGLE_API_KEY4=${GOOGLE_API_KEY4}
      - GOOGLE_SEARCH_ENGINE_ID4=${GOOGLE_SEARCH_ENGINE_ID4}
      - GOOGLE_API_KEY5=${GOOGLE_API_KEY5}
      - GOOGLE_SEARCH_ENGINE_ID5=${GOOGLE_SEARCH_ENGINE_ID5}
      - GOOGLE_API_KEY6=${GOOGLE_API_KEY6}
      - GOOGLE_SEARCH_ENGINE_ID6=${GOOGLE_SEARCH_ENGINE_ID6}
  frontend:
    build: frontend
    ports:
      - '4200:4200'
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - GEMINI_KEY=${GEMINI_KEY}
      - SERPAPI_KEY=${SERPAPI_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CSE_ID=${CSE_ID}
      - GOOGLE_SEARCH_SERVER=${GOOGLE_SEARCH_SERVER}
      - DATABASE_URL=${DATABASE_URL}
      - CLIENT_ID=${CLIENT_ID}        