services:
 - type: web
   name: backend
   env: docker
   plan: starter
   dockerfilePath: ./backend/Dockerfile
   autoDeploy: true
   envVars:
    - key: SECRET_KEY
      sync: false
    - key: DEBUG
      sync: false
    - key: ALLOWED_HOSTS
      sync: false
    - key: GEMINI_KEY
      sync: false
    - key: SERPAPI_KEY
      sync: false
    - key: GOOGLE_API_KEY
      sync: false
    - key: CSE_ID
      sync: false
    - key: GOOGLE_SEARCH_SERVER
      sync: false
    - key: DATABASE_URL
      sync: false
    - key: CLIENT_ID
      sync: false

 - type: web
   name: googlesearchserver
   env: docker
   plan: starter
   dockerfilePath: ./googlesearchserver/Dockerfile
   autoDeploy: true
   envVars:
    - key: GOOGLE_API_KEY1
      sync: false
    - key: GOOGLE_SEARCH_ENGINE_ID1
      sync: false
    - key: GOOGLE_API_KEY2
      sync: false
    - key: GOOGLE_SEARCH_ENGINE_ID2
      sync: false
    - key: GOOGLE_API_KEY3
      sync: false
    - key: GOOGLE_SEARCH_ENGINE_ID3
      sync: false
    - key: GOOGLE_API_KEY4
      sync: false
    - key: GOOGLE_SEARCH_ENGINE_ID4
      sync: false
    - key: GOOGLE_API_KEY5
      sync: false
    - key: GOOGLE_SEARCH_ENGINE_ID5
      sync: false
    - key: GOOGLE_API_KEY6
      sync: false
    - key: GOOGLE_SEARCH_ENGINE_ID6
      sync: false

 - type: web
   name: frontend
   env: docker
   plan: starter
   dockerfilePath: ./frontend/Dockerfile
   autoDeploy: true
   envVars:
    - key: SECRET_KEY
      sync: false
    - key: DEBUG
      sync: false
    - key: ALLOWED_HOSTS
      sync: false
    - key: GEMINI_KEY
      sync: false
    - key: SERPAPI_KEY
      sync: false
    - key: GOOGLE_API_KEY
      sync: false
    - key: CSE_ID
      sync: false
    - key: GOOGLE_SEARCH_SERVER
      sync: false
    - key: DATABASE_URL
      sync: false
    - key: CLIENT_ID
      sync: false
