# Generated by Django 5.2.6 on 2025-09-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('given_name', models.CharField(max_length=50)),
                ('family_name', models.CharField(max_length=50)),
                ('unique_id', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('jwt_id', models.TextField()),
            ],
        ),
    ]
