# Generated by Django 5.2.6 on 2025-09-22 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jwt_id',
        ),
    ]
