# Generated by Django 5.2.6 on 2025-09-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_user_jwt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(max_length=500),
        ),
    ]
