# Generated by Django 5.2.6 on 2025-09-22 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_user_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
    ]
