# Generated by Django 5.2.6 on 2025-09-30 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='family_name',
        ),
    ]
