# Generated by Django 5.2.6 on 2025-09-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DraftGenerator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
