# Generated by Django 5.2.6 on 2025-09-22 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DraftGenerator', '0002_draft_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='website',
        ),
    ]
