# Generated by Django 5.2.6 on 2025-09-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DraftGenerator', '0003_remove_draft_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='content',
            field=models.JSONField(),
        ),
    ]
