# Generated by Django 5.2.6 on 2025-09-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DraftGenerator', '0004_alter_draft_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
